### ISSUE TITLE
hello,where is the requirements.txt?

### ISSUE THREAD

**Issue by HackJH** [fubel/stmc#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Please provide the following information:
- Output of `pip freeze` and or `conda info`
- Output of `python -m torch.utils.collect_env`

**Additional context**

**Comment by fubel** [comment]
Hi,

after installing torch, torchvision and rama, these requirements should suffice:

```
hydra-core==1.3.2
loguru==0.7.2
matplotlib==3.7.1
motmetrics==1.4.0
numpy==1.23.5
omegaconf==2.3.0
pandas==2.0.2
Pillow==11.0.0
pycocotools==2.0.8
pytrec_eval==0.5
qqdm==0.0.7
scikit_learn==1.2.2
scipy==1.14.1
setuptools==70.0.0
tabulate==0.9.0
```

Please let me know if you see any setup issues.

**Comment by HackJH** [comment]
thank for your review！looking forward to your future releases
